# Generated by Django 5.1.4 on 2024-12-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_theatre_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theatre',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
