# Generated by Django 5.1.4 on 2024-12-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_theatre_location_alter_theatre_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theatre',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
