# Generated by Django 5.1.4 on 2024-12-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_theatre_location_alter_theatre_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
