# Generated by Django 5.1.4 on 2024-12-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='location',
        ),
        migrations.AlterField(
            model_name='theatre',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatres', to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
