# Generated by Django 5.1.4 on 2024-12-16 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_theatre_location_alter_theatre_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='theatre',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theatres', to='accounts.userlocation'),
            preserve_default=False,
        ),
    ]
