# Generated by Django 5.1.4 on 2024-12-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_theatre_latitude_remove_theatre_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theatre',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theatre',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Theatres', to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
