# Generated by Django 5.1.4 on 2024-12-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_theatre_latitude_theatre_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='longitude',
        ),
    ]
