# Generated by Django 5.1.4 on 2024-12-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_theatre_latitude_remove_theatre_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
